### ISSUE TITLE
Beginner friendly

### ISSUE THREAD

**Issue by Simon-Lavery** [Simon-Lavery/SLTaxi-website#2]
This repo is open to contributors of all skill levels.

I am a beginner so if you think you can help or you think I can help you get involved 

A good place to start might be with me over the next few weeks trying to convert all CSS to great SCSS

**Comment by Assone** [comment]
Do you still need to convert css to scss, I can help you.

**Comment by Simon-Lavery** [comment]
I have converted alot of it but I just learned SASS so your welcome to add to it or change anything you think needs improved, that goes for any part of the code

**Comment by Assone** [comment]
ok, Let me see what I can change.

**Comment by Assone** [comment]
Hey, there seems to be a file missing from the esj template.
```
Error: Could not find the include file "./partials/google-analytics"
    at getIncludePath (/Users/reset0/Development/OpenSource/SLTaxi-website/node_modules/ejs/lib/ejs.js:162:13)
    at includeSource (/Users/reset0/Development/OpenSource/SLTaxi-website/node_modules/ejs/lib/ejs.js:306:17)
    at /Users/reset0/Development/OpenSource/SLTaxi-website/node_modules/ejs/lib/ejs.js:702:26
    at Array.forEach (<anonymous>)
    at Template.generateSource (/Users/reset0/Development/OpenSource/SLTaxi-website/node_modules/ejs/lib/ejs.js:678:15)
    at Template.compile (/Users/reset0/Development/OpenSource/SLTaxi-website/node_modules/ejs/lib/ejs.js:557:12)
    at Object.compile (/Users/reset0/Development/OpenSource/SLTaxi-website/node_modules/ejs/lib/ejs.js:389:16)
    at handleCache (/Users/reset0/Development/OpenSource/SLTaxi-website/node_modules/ejs/lib/ejs.js:212:18)
    at tryHandleCache (/Users/reset0/Development/OpenSource/SLTaxi-website/node_modules/ejs/lib/ejs.js:251:16)
    at View.exports.renderFile [as engine] (/Users/reset0/Development/OpenSource/SLTaxi-website/node_modules/ejs/lib/ejs.js:482:10)
```
I can't run this website. In your `index.js` file, The part about URL jumping, You can put it in the route.

**Comment by Simon-Lavery** [comment]
Hi sorry, I am not at the computer today, I put the google analytics script in ejs file and must have added it to git ignore, it should work fine in you delete the line where its included

**Comment by Simon-Lavery** [comment]
> Hey, there seems to be a file missing from the esj template.
> 
> ```
> Error: Could not find the include file "./partials/google-analytics"
>     at getIncludePath (/Users/reset0/Development/OpenSource/SLTaxi-website/node_modules/ejs/lib/ejs.js:162:13)
>     at includeSource (/Users/reset0/Development/OpenSource/SLTaxi-website/node_modules/ejs/lib/ejs.js:306:17)
>     at /Users/reset0/Development/OpenSource/SLTaxi-website/node_modules/ejs/lib/ejs.js:702:26
>     at Array.forEach (<anonymous>)
>     at Template.generateSource (/Users/reset0/Development/OpenSource/SLTaxi-website/node_modules/ejs/lib/ejs.js:678:15)
>     at Template.compile (/Users/reset0/Development/OpenSource/SLTaxi-website/node_modules/ejs/lib/ejs.js:557:12)
>     at Object.compile (/Users/reset0/Development/OpenSource/SLTaxi-website/node_modules/ejs/lib/ejs.js:389:16)
>     at handleCache (/Users/reset0/Development/OpenSource/SLTaxi-website/node_modules/ejs/lib/ejs.js:212:18)
>     at tryHandleCache (/Users/reset0/Development/OpenSource/SLTaxi-website/node_modules/ejs/lib/ejs.js:251:16)
>     at View.exports.renderFile [as engine] (/Users/reset0/Development/OpenSource/SLTaxi-website/node_modules/ejs/lib/ejs.js:482:10)
> ```
> 
> I can't run this website. In your `index.js` file, The part about URL jumping, You can put it in the route.

I had included the google analytics partial in the .gitignore file, I am just getting used to github and wasn't sure if it could be uploaded but it can, should work fine now

**Comment by Assone** [comment]
cool , I'll try now.
